import 'package:flutter/material.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:flutter_svg/flutter_svg.dart';
import 'package:get/get.dart';
import '../../../res/colors/colors.dart';
import '../../../res/fonts/textstyle.dart';
import '../../../widgets/backbutton_widget.dart';
// import '../../../res/assets/asset.dart'; // Assuming ImageAssets and SvgAssets are defined

// --- Data Structure for FAQs ---
class FAQItem {
  final String category;
  final String question;
  final String answer;

  FAQItem({required this.category, required this.question, required this.answer});
}

// --- Sub Views ---

// Updated FAQView to include sub-tabs
class FAQView extends StatelessWidget {
   FAQView({super.key});

  final List<FAQItem> allFaqs = [
    FAQItem(category: 'General', question: 'How do I start a workout plan?', answer: 'You can select a predefined plan from the "Trainings" tab, or create a custom plan tailored to your goals. Our app guides you through step-by-step instructions and video demonstrations.'),
    FAQItem(category: 'General', question: 'Is the app compatible with my device?', answer: 'The app is compatible with most modern iOS and Android devices. Ensure your operating system is up-to-date for the best experience.'),
    FAQItem(category: 'Account', question: 'How can I reset my password?', answer: 'Go to the "Sign In" screen and click "Forgot Password". You will receive an email or OTP to reset your credentials.'),
    FAQItem(category: 'Account', question: 'How do I change my subscription plan?', answer: 'Navigate to "Settings" > "Subscription". Here you can view, upgrade, or downgrade your current plan.'),
    FAQItem(category: 'Services', question: 'Do you offer personalized meal plans?', answer: 'Yes, our premium service includes personalized meal plans generated by our AI based on your dietary restrictions and fitness goals.'),
    FAQItem(category: 'Services', question: 'What types of exercises are included?', answer: 'We offer a wide range of exercises including strength, cardio, yoga, and HIIT, all with detailed instructions and video guides.'),
  ];

  @override
  Widget build(BuildContext context) {
    // Using DefaultTabController for the inner tabs (General, Account, Services)
    return DefaultTabController(
      length: 3,
      child: Column(
        children: [
          // --- Secondary Tab Bar (General, Account, Services) ---
          Container(
            height: 40.h,
            margin: EdgeInsets.symmetric(horizontal: 20.w),
            decoration: BoxDecoration(
              color: AppColor.black111214, // Same background color
              borderRadius: BorderRadius.circular(10.r),
              border: Border.all(color: AppColor.gray374151, width: 1), // Subtle border
            ),
            child: TabBar(
              indicator: BoxDecoration(
                borderRadius: BorderRadius.circular(10.r),
                color: AppColor.customPurple, // Active tab background is white
              ),
              labelColor: AppColor.black111214, // Active label is dark text
              unselectedLabelColor: AppColor.white.withOpacity(0.7), // Inactive label is light text
              labelStyle: AppTextStyles.poppinsBold.copyWith(fontSize: 14.sp),
              unselectedLabelStyle: AppTextStyles.poppinsMedium.copyWith(fontSize: 14.sp),
              indicatorSize: TabBarIndicatorSize.tab,
              indicatorPadding: EdgeInsets.zero,
              indicatorWeight: 0,
              dividerColor: Colors.transparent,
              tabs: const [
                Tab(text: 'General'),
                Tab(text: 'Account'),
                Tab(text: 'Services'),
              ],
            ),
          ),

          SizedBox(height: 10.h),

          // --- Tab Views Content ---
          Expanded(
            child: TabBarView(
              children: [
                // 1. General FAQs
                _buildFaqList(allFaqs.where((faq) => faq.category == 'General').toList()),

                // 2. Account FAQs
                _buildFaqList(allFaqs.where((faq) => faq.category == 'Account').toList()),

                // 3. Services FAQs
                _buildFaqList(allFaqs.where((faq) => faq.category == 'Services').toList()),
              ],
            ),
          ),
        ],
      ),
    );
  }

  // Helper method to build the list of ExpansionTiles
  Widget _buildFaqList(List<FAQItem> faqs) {
    return SingleChildScrollView(
      padding: EdgeInsets.only(left: 20.w, right: 20.w, bottom: 20.h),
      child: Column(
        children: faqs.map((faq) => Padding(
          padding: EdgeInsets.only(bottom: 5.h), // Spacing between items
          child: Theme(
            data: ThemeData(dividerColor: AppColor.gray374151), // Customize the ExpansionTile divider
            child: ExpansionTile(
              tilePadding: EdgeInsets.zero,
              collapsedIconColor: AppColor.white.withOpacity(0.7),
              iconColor: AppColor.customPurple,
              title: Text(
                faq.question, // Changed from 'Lorem ipsum dolor sit amet?'
                style: AppTextStyles.poppinsMedium.copyWith(
                  color: AppColor.white,
                  fontSize: 16.sp,
                ),
              ),
              children: <Widget>[
                Padding(
                  padding: EdgeInsets.only(bottom: 10.h),
                  child: Text(
                    faq.answer, // Display the actual answer
                    style: AppTextStyles.poppinsRegular.copyWith(
                      color: AppColor.gray9CA3AF,
                      fontSize: 14.sp,
                      height: 1.4,
                    ),
                  ),
                ),
              ],
            ),
          ),
        )).toList(),
      ),
    );
  }
}

// Custom View for when the "Contact Us" tab is selected (Kept for completeness)
class ContactUsView extends StatelessWidget {
   ContactUsView({super.key});


  final List<Map<String, dynamic>> faqs = [
    const {'title': 'Customer service', 'icon': Icons.headset_mic_outlined},
    const {'title': 'Website', 'icon': Icons.language_outlined},
    {'title': 'Whatsapp', 'icon': Icons.whatshot_sharp},
    const {'title': 'Facebook', 'icon': Icons.facebook_outlined},
    const {'title': 'Instagram', 'icon': Icons.camera_alt_outlined},
  ];

  @override
  Widget build(BuildContext context) {
    return Column(
      children: faqs.map((item) {
        return ExpansionTile(
          collapsedIconColor: AppColor.white,
          iconColor: AppColor.customPurple,
          title: Row(
            children: [
              Icon(item['icon'] as IconData, color: AppColor.customPurple, size: 28.sp),
              SizedBox(width: 15.w),
              Text(
                item['title'] as String,
                style: AppTextStyles.poppinsMedium.copyWith(
                  color: AppColor.white,
                  fontSize: 16.sp,
                ),
              ),
            ],
          ),
          children: <Widget>[
            Padding(
              padding: EdgeInsets.symmetric(horizontal: 20.w, vertical: 10.h),
              child: Text(
                'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
                style: AppTextStyles.poppinsRegular.copyWith(
                  color: AppColor.gray9CA3AF,
                  fontSize: 14.sp,
                ),
              ),
            ),
          ],
        );
      }).toList(),
    );
  }
}


// --- Main Page Implementation (Updated to integrate the new FAQView) ---
class HelpAndFaqsPage extends StatelessWidget {
  const HelpAndFaqsPage({super.key});

  @override
  Widget build(BuildContext context) {
    return DefaultTabController(
      length: 2, // Main tabs: FAQ and Contact Us
      child: Scaffold(
        backgroundColor: AppColor.black111214,
        appBar: AppBar(
          backgroundColor: AppColor.black111214,
          elevation: 0,
          leading: const BackButtonBox(),
          title: Text(
            'Help & FAQs',
            style: AppTextStyles.poppinsBold.copyWith(
              color: AppColor.white,
              fontSize: 22.sp,
            ),
          ),
        ),
        body: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Padding(
              padding: EdgeInsets.symmetric(horizontal: 20.w, vertical: 10.h),
              child: Text(
                'How Can We Help You?',
                style: AppTextStyles.poppinsMedium.copyWith(
                  color: AppColor.white,
                  fontSize: 18.sp,
                ),
              ),
            ),

            // --- Primary Tab Bar (FAQ vs. Contact Us) ---
            Padding(
              padding: EdgeInsets.symmetric(horizontal: 20.w, vertical: 10.h),
              child: Container(
                height: 40.h,
                decoration: BoxDecoration(
                  color: AppColor.black111214,
                  borderRadius: BorderRadius.circular(15.r),
                ),
                child: TabBar(
                  indicator: BoxDecoration(
                    borderRadius: BorderRadius.circular(15.r),
                    color: AppColor.customPurple, // Active tab background color
                  ),
                  labelColor: AppColor.white,
                  labelPadding: EdgeInsets.zero,
                  unselectedLabelColor: AppColor.white.withOpacity(0.7),
                  labelStyle: AppTextStyles.poppinsBold.copyWith(fontSize: 16.sp),
                  unselectedLabelStyle: AppTextStyles.poppinsMedium.copyWith(fontSize: 16.sp),
                  indicatorSize: TabBarIndicatorSize.tab,
                  indicatorPadding: EdgeInsets.zero,
                  indicatorWeight: 0,
                  dividerColor: Colors.transparent, // Remove divider line
                  tabs: const [
                    Tab(text: 'FAQ'),
                    Tab(text: 'Contact Us'),
                  ],
                ),
              ),
            ),

            // --- Tab Views Content ---
            Expanded(
              child: TabBarView(
                children: [
                  // 1. FAQ Tab Content (Now uses inner tabs)
                   FAQView(),

                  // 2. Contact Us Tab Content
                   ContactUsView(),
                ],
              ),
            ),
          ],
        ),
      ),
    );
  }
}
