import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_messaging/firebase_messaging.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_dotenv/flutter_dotenv.dart';
import 'package:flutter_local_notifications/flutter_local_notifications.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:get/get.dart';
import 'package:get_storage/get_storage.dart';

import 'app/modules/workout/views/excercisedetails.dart';
import 'firebase_options.dart'; // ← GENERATED BY flutterfire configure

import 'app/constants/push_notification.dart';
import 'app/modules/auth/controllers/authcontroller.dart';
import 'app/modules/home/controllers/calender_controller.dart';
import 'app/modules/home/controllers/navcontroller.dart';
import 'app/modules/home/service/home_service.dart';
import 'app/modules/nutrition/controllers/nutri_controller.dart';
import 'app/modules/onboard/controllers/onboard_controller.dart';
import 'app/modules/onboard/views/splashview.dart';
import 'app/modules/setup/controllers/bottomsheetcontroller.dart';
import 'app/modules/setup/controllers/schedule_controller.dart';
import 'app/modules/setup/controllers/setup_controller.dart';
import 'app/modules/setup/service/service.dart';
import 'app/modules/setting/controller/profilecontroller.dart';
import 'app/modules/setting/controller/setting_controller.dart';
import 'app/modules/setting/service/setting_service.dart';
import 'app/modules/workout/controllers/workoutcontroller.dart';
import 'app/modules/workout/services/workout_services.dart';
import 'app/res/colors/colors.dart';

// Global instance for local notifications
final FlutterLocalNotificationsPlugin flutterLocalNotificationsPlugin =
FlutterLocalNotificationsPlugin();

// Background message handler
Future<void> _firebaseMessagingBackgroundHandler(RemoteMessage message) async {
  // Initialize Firebase in background
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  print('🔔 Background message handled: ${message.messageId}');
  // Add your notification handling logic here if needed
}

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // 1. Load .env file (secrets like RevenueCat key)
  try {
    await dotenv.load(fileName: ".env");
    print('✅ .env loaded successfully');
  } catch (e) {
    print('❌ Failed to load .env: $e');
    // Continue anyway (you can add fallback keys if needed)
  }

  // 2. Initialize Firebase (critical for firebase_messaging, etc.)
  try {
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );
    print('✅ Firebase initialized');
  } catch (e) {
    print('❌ Firebase init failed: $e');
  }

  // 3. Set background message handler
  FirebaseMessaging.onBackgroundMessage(_firebaseMessagingBackgroundHandler);

  const AndroidInitializationSettings initializationSettingsAndroid =
  AndroidInitializationSettings('@mipmap/ic_launcher');

  const DarwinInitializationSettings initializationSettingsIOS =
  DarwinInitializationSettings(
    requestSoundPermission: true,
    requestBadgePermission: true,
    requestAlertPermission: true,
  );

  const InitializationSettings initializationSettings = InitializationSettings(
    android: initializationSettingsAndroid,
    iOS: initializationSettingsIOS,
  );

  await flutterLocalNotificationsPlugin.initialize(
    initializationSettings,
    onDidReceiveNotificationResponse: (NotificationResponse response) {
      // Handle notification tapped logic here
      print('Notification tapped: ${response.payload}');
    },
  );
  // 5. Other initializations
  await GetStorage.init();
  await SystemChrome.setPreferredOrientations([DeviceOrientation.portraitUp]);

  // 6. Register all GetX controllers/services
  Get.put(SetupService());
  Get.put(HomeService());
  Get.put(OnboardController());
  Get.put(NutritionController());
  Get.put(BottomSheetController());
  Get.put(SetupController());
  Get.put(Authcontroller());
  Get.put(GalleryController());
  Get.put(NavController());
  Get.put(ScheduleController());
  Get.put(ProfileController());
  Get.put(WorkoutService());
  Get.put(WorkoutController());
  Get.put(VideoCleanupHelper(), permanent: true);
  Get.put(SettingService());
  Get.put(Settingcontroller());

  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return ScreenUtilInit(
      designSize: const Size(360, 690),
      minTextAdapt: true,
      splitScreenMode: true,
      builder: (context, child) {
        print('ScreenUtil scaleWidth: ${ScreenUtil().scaleWidth}');
        return GestureDetector(
          onTap: () {
            FocusManager.instance.primaryFocus?.unfocus();
          },
          child: GetMaterialApp(
            debugShowCheckedModeBanner: false,
            title: "Kenzeno",
            theme: ThemeData(
              scaffoldBackgroundColor: AppColor.black111214,
              appBarTheme: const AppBarTheme(
                elevation: 0,
                backgroundColor: AppColor.black111214,
                scrolledUnderElevation: 0,
              ),
            ),
            home: const SplashView(),
          ),
        );
      },
    );
  }
}